# Generated by Django 4.1 on 2022-11-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentname', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('RegNO', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('Taluka', models.CharField(max_length=15)),
                ('District', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Subject', models.CharField(choices=[('TOC', 'TOC'), ('PYTHON', 'PYTHON'), ('SOFTWARE ENGINEERING', 'SOFTWARE ENGINEERING'), ('OS', 'OS'), ('DBMS', 'DBMS')], max_length=20)),
                ('Feedback_stu', models.CharField(max_length=150)),
                ('regNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sudent_Faculty.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalmarks', models.IntegerField()),
                ('Semester', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
                ('regNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sudent_Faculty.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BTECH', 'BTECH')], max_length=20)),
                ('branch', models.CharField(choices=[('MECH', 'MECH'), ('ELECTRICAL', 'ELECTRICAL'), ('CHEM', 'Chemical'), ('IT', 'IT'), ('CSE', 'CSE')], max_length=20)),
                ('Year', models.IntegerField(default=2022)),
                ('Date_Admission', models.DateTimeField()),
                ('Semester', models.CharField(max_length=20)),
                ('nameStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studentname_Student_set', to='Sudent_Faculty.student_info')),
                ('regNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegNO_Student_set', to='Sudent_Faculty.student_info')),
            ],
        ),
    ]
